version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: task_db

  app:
    build: .
    container_name: darqube-python-task
    command: uvicorn task_app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"
    environment:
      MONGODB_URL: mongodb://root:example@mongo/task_db?authSource=admin
    volumes:
      - ./task_app:/app/task_app
    depends_on:
      - mongo